package LukeS26.github.io.dataschema;

import org.bson.Document;
import org.bson.types.ObjectId;

public class Post extends DataSchema {
    public ObjectId id;
    public String author;
    public String title;
    public String body;

    /**
     * Converts this Post object into a document Posts converted into documents
     * won't have an ID, since the ID is generated by MongoDB and this will be used
     * by docs that may not be in the database yet.
     * 
     * @return Document containing post information
     */
    @Override
    public Document toDoc() {
        Document postDoc = new Document("author", author).append("title", title).append("body", body);
        return postDoc;
    }

    public static Post fromDoc(Document doc) {
        Post p = new Post();
        p.id = (ObjectId) doc.get("_id");
        p.author = (String) doc.get("author");
        p.title = (String) doc.get("title");
        p.body = (String) doc.get("body");

        return p;
    }
}
